dist: bionic

language: python

python: 3.7

services:
  - docker

jobs:
  include:
    - stage: Run tests
      name: QGIS Desktop
      install:
        - cd .docker
        - ./start.sh
      script:
        - ./exec.sh

    - stage: Push translations to Transifex
      if: branch = master AND type != pull_request
      install:
        - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
      script: qgis-plugin-ci push-translation ${TX_TOKEN}

    - stage: Deploy
      if: tag IS present
      name: Create release, plugins.qgis.org
      install:
        - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
      before_deploy:
        - export RELEASE_TITLE=${TRAVIS_TAG:1}
      script:
        - qgis-plugin-ci -v
      deploy:
        - provider: releases
          edge: true
          file: .
          name: ${RELEASE_TITLE}
          api_key: ${GH_TOKEN}
          on:
            tags: true

        - provider: script
          script: qgis-plugin-ci release ${TRAVIS_TAG} --transifex-token ${TX_TOKEN} --github-token ${GH_TOKEN} --osgeo-username ${OSGEO_USERNAME} --osgeo-password ${OSGEO_PASSWORD} --allow-uncommitted-changes
          on:
            tags: true

        - provider: script
          skip_cleanup: true
          script: ./github/push.sh
          on:
            tags: true